n = input('Digite algo: ')
print('O tipo primitivo {}', type(n))
print('So tem espaço? ', n.isspace())
print('É um numero? ', n.isnumeric())
print('É alfabetico? ', n.isalpha())
print('É alfanumerico?', n.isalnum())
print('Está maiúsculo? ', n.isupper())
print('ESta minuscula? ', n.islower())
print('Está capitalizada? ', n.istitle())
